# Automates creation of Release Drafts using Release Drafter
# More Info: https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.adoc

---
name: 'Release Drafter'

on:
  push:
    branches:
      - master
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# The release drafter config starts here
# Save this as .github/release-drafter.yml
template: |
  ## What's Changed
  $CHANGES

  **Full Changelog**: https://github.com/$REPOSITORY/compare/$PREVIOUS_TAG...$NEW_TAG

categories:
  - title: 'ğŸš€ Features'
    labels:
      - feature
  - title: 'ğŸ› Bug Fixes'
    labels:
      - bug
  - title: 'ğŸ›  Maintenance'
    labels:
      - maintenance

change-template: '* $TITLE (#$NUMBER) by @$AUTHOR'
no-changes-template: '* No changes in this release.'
